### ISSUE TITLE
Usability fix

### ISSUE THREAD

**Issue by kornpow** [pl31/python-liquidcrystal_i2c#2]
Hi, I am going to use this library for a project I think, I hope I could potentially help contribute some of the missing function potentially too. Just getting starting with using the library, I noticed that if you write to a line, it just right shifts the text currently on that line. My workaround for this, which maybe useful to add in is:
lcd.printline(0,"Text String".ljust(20," "))
The ljust command fills in the remaining characters with spaces. I think this makes more sense for usability.

**Comment by pl31** [comment]
Hi. I use it like this here:
```
line1 = get_ip(interface).rjust(16)
line2 = '{}{:9d} pkt/s'.format(indicator, rx_packets_delta)
lcd.printline(0, line1)
lcd.printline(1, line2)
```

this is similar to what you do.

You prefer, that printline automatically fills the rest of the line with spaces?

**Comment by kornpow** [comment]
Yes I ended up doing similar to what you were saying. Id prefer it that way for printline, as I think that is the primary use case. I'd think if there was a print command it wouldnt fill in the line, but printline I think should. Just an idea though,
