### ISSUE TITLE
IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by lucasjwilliams** [pl31/python-liquidcrystal_i2c#3]
> Traceback (most recent call last):
>  File "lcd2004.py", line 13, in <module>
>    lcd = liquidcrystal_i2c.LiquidCrystal_I2C(0x3f, 1, numlines=4)
>  File "build/bdist.linux-armv7l/egg/liquidcrystal_i2c/liquidcrystal_i2c.py", line 70, in __init__
>  File "build/bdist.linux-armv7l/egg/liquidcrystal_i2c/liquidcrystal_i2c.py", line 243, in _expanderWrite
>IOError: [Errno 5] Input/output error

Hi I have this error pop up when I start my program.
It was working fine before but I then unplugged all my pins to use them for another project. I plugged it back in and I have this error, I have triple checked that they are all on the correct pins.

Any ideas what is causing this?

**Comment by pl31** [comment]
Hi Lucas,

no clue, sorry. I currently do not have the hardware here, so I can't even test. Did you setup a new OS? Which Raspi are you using? Input/Output error might be related to access right, like described here:
https://github.com/pl31/python-liquidcrystal_i2c#access-rights

Cheers
Patrick

**Comment by lucasjwilliams** [comment]
Hi Patrick,

Thanks for your help I ended up moving my script to another file and it worked fine. The error is still the same in the original location which makes no sense because it was working fine a few days ago. I haven't changed the OS or updated/upgraded the Pi, and I believe it is a RaspPi 3 B+.

Lucas
