### ISSUE TITLE
AttributeError: 'module' object has no attribute

### ISSUE THREAD

**Issue by nathan3453** [pl31/python-liquidcrystal_i2c#5]
lcd line is not working?

AttributeError: 'module' object has no attribute 'LiquidCrystal_I2C'

import liquidcrystal_i2c

cols = 20
rows = 4

import liquidcrystal_i2c
lcd = liquidcrystal_i2c.LiquidCrystal_I2C(0x27, 1, numlines=rows)
  
lcd.printline(0, 'LCM2004 IIC V2'.center(cols))
lcd.printline(1, 'and'.center(cols))
lcd.printline(2, 'python-')
lcd.printline(3, 'liquidcrystal_i2c'.rjust(cols))

**Comment by pl31** [comment]
Did you follow the instructions here:
https://github.com/pl31/python-liquidcrystal_i2c?tab=readme-ov-file#install
